<?php

use App\Http\Controllers\EventControllerABC;
use App\Http\Controllers\RegistrationControllerABC;
use App\Http\Controllers\DashboardControllerABC;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('dashboard');
});

// Auth routes (auto-generated by Breeze)
require __DIR__.'/auth.php';

// Protected routes - use middleware here instead of in controllers
Route::middleware(['auth'])->group(function () {
    // Dashboard
    Route::get('/dashboard', [DashboardControllerABC::class, 'index'])->name('dashboard');
    
    // Event routes
    Route::get('/events', [EventControllerABC::class, 'index'])->name('events.index');
    Route::get('/events/create', [EventControllerABC::class, 'create'])->name('events.create');
    Route::post('/events', [EventControllerABC::class, 'store'])->name('events.store');
    Route::get('/events/{event}', [EventControllerABC::class, 'show'])->name('events.show');
    Route::get('/events/{event}/edit', [EventControllerABC::class, 'edit'])->name('events.edit');
    Route::put('/events/{event}', [EventControllerABC::class, 'update'])->name('events.update');
    Route::delete('/events/{event}', [EventControllerABC::class, 'destroy'])->name('events.destroy');
    
    // Calendar
    Route::get('/calendar', [EventControllerABC::class, 'calendar'])->name('events.calendar');
    
    // Registration routes
    Route::post('/events/{event}/register', [RegistrationControllerABC::class, 'register'])->name('registrations.register');
    Route::delete('/events/{event}/cancel', [RegistrationControllerABC::class, 'cancel'])->name('registrations.cancel');
    Route::patch('/registrations/{registration}/approve', [RegistrationControllerABC::class, 'approve'])->name('registrations.approve');
    Route::patch('/registrations/{registration}/decline', [RegistrationControllerABC::class, 'decline'])->name('registrations.decline');
});